apiVersion: v1

kind: PersistentVolumeClaim # Create PVC
metadata:
  namespace: dpetrocelli
  name: postgres-volume-claim # Sets PVC's name
  labels:
    app: postgres # Defines app to create PVC for
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Sets PVC's size