apiVersion: v1
kind: Service # Create service

metadata:
  namespace: default
  name: postgres # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  type: ClusterIP # Sets the service type
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
 # Sets the port to run the postgres application
  selector:
    app: postgres


