apiVersion: v1
kind: Service # Create service

metadata:
  namespace: dpetrocelli
  name: postgres # Sets the service name
  labels:
    app: postgres # Defines app to create service for
spec:
  type: LoadBalancer # Sets the service type
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
 # Sets the port to run the postgres application
  selector:
    app: postgres



  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: strongpasswordapp
  postgres-dpetrocelli.cloud.okteto.net