name: First Node Pipeline 

on:
  push:
    branches:
      - main


jobs:
  setup-stage:
    outputs:
      env-name: ${{ steps.env-name.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: echo "env=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  build:
    needs: [setup-stage] 
    
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ needs.setup-stage.outputs.env-name }}
      
    env:
      # secrets -> https://github.com/dpetrocelli/unlu-content/settings/secrets/actions
      
      name: ${{ needs.setup-stage.outputs.env-name }}
      PORT: ${{ secrets.PORT }}
      CLIENT_ORIGIN_URL: ${{ secrets.CLIENT_ORIGIN_URL }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
    
    steps:
      # STEP 0 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # STEP 2 - Build JAR based on env vars (taken from secrets) 
      - name: Run ls command
        working-directory: sd/main_concepts/09_nodejs_pipeline
        run: |
          ls -lah
          
      - name: Run npm install commands
        working-directory: sd/main_concepts/09_nodejs_pipeline
        run: |
          npm install
          npm install dependency-check -g

      - name: Run npm check dependencies
        working-directory: sd/main_concepts/09_nodejs_pipeline
        run: |
          dependency-check ./package.json --verbose
          
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  #   publish-gpr:
  #       needs: build
  #       runs-on: ubuntu-latest
  #       steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-node@v1
  #           with:
  #           node-version: 12
  #           registry-url: https://npm.pkg.github.com/
  #           scope: '@your-github-username'
  #       - run: npm ci
  #       - run: npm publish
  #           env:
  #           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
