name: SIP Pipeline

on:
  push:
    branches:
      - main

 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EZORED_AWS_KEY_ID: ${{ env.EZORED_AWS_KEY_ID }}
      EZORED_AWS_SECRET_KEY: ${{ env.EZORED_AWS_SECRET_KEY }}
    
    steps:
      # STEP 0 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # STEP 1 - Configure environment (JDK 17 + ?)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      
      # STEP 2 - Build JAR based on env vars (taken from secrets) 
      - name: Run build with Gradle Wrapper
        working-directory: sip/oauth-demo/api_spring_java_hello-world
        run: |
          ls -lah 
          ./gradlew build
          java -jar build/libs/*.jar
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  #   publish-gpr:
  #       needs: build
  #       runs-on: ubuntu-latest
  #       steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-node@v1
  #           with:
  #           node-version: 12
  #           registry-url: https://npm.pkg.github.com/
  #           scope: '@your-github-username'
  #       - run: npm ci
  #       - run: npm publish
  #           env:
  #           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
