name: SIP Pipeline

on:
  push:
    branches:
      - main

 

jobs:
  setup-stage:
    outputs:
      env-name: ${{ steps.env-name.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Name
        id: env-name
        run: echo "env=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  build:
    needs: [setup-stage] 
    
    runs-on: ubuntu-latest
    
    environment: 
      name: ${{ needs.setup-stage.outputs.env-name }}
      
    env:
      # secrets -> https://github.com/dpetrocelli/unlu-content/settings/secrets/actions
      
      name: ${{ needs.setup-stage.outputs.env-name }}
      PORT: ${{ secrets.PORT }}
      CLIENT_ORIGIN_URL: ${{ secrets.CLIENT_ORIGIN_URL }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
    
    steps:
      # STEP 0 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # STEP 1 - Configure environment (JDK 17 + ?)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      
      # STEP 2 - Build JAR based on env vars (taken from secrets) 
      - name: Run build with Gradle Wrapper
        working-directory: sip/oauth-demo/api_spring_java_hello-world
        run: |
          ls -lah 
          echo branch_name: '${name}'
          echo PORT: '${PORT}'
          echo CLIENT_ORIGIN_URL: '${CLIENT_ORIGIN_URL}'
          echo AUTH0_DOMAIN: '${AUTH0_DOMAIN}'
        
          #./gradlew build
          #java -jar build/libs/*.jar
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}


  #   publish-gpr:
  #       needs: build
  #       runs-on: ubuntu-latest
  #       steps:
  #       - uses: actions/checkout@v2
  #       - uses: actions/setup-node@v1
  #           with:
  #           node-version: 12
  #           registry-url: https://npm.pkg.github.com/
  #           scope: '@your-github-username'
  #       - run: npm ci
  #       - run: npm publish
  #           env:
  #           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
